version: "3"

services:
    db:
        image: mysql:8.0.33
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3306:3306
        networks:
            - symfony_app
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - code:/var/www/symfony:rw
#            - symfony_app_var:/var/www/symfony/var
#            - symfony_app_vendor:/var/www/symfony/vendor
        networks:
            - symfony_app
    nginx:
        build:
            context: ./nginx
        volumes:
            - code:/var/www/symfony:rw
#            - symfony_app_var:/var/www/symfony/var
#            - symfony_app_vendor:/var/www/symfony/vendor
        ports:
            - 80:80
        networks:
            - symfony_app
        env_file:
            - .env.nginx.local


    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
        networks:
            - symfony_app

    redis:
        restart: unless-stopped
        image: redis:5-alpine
        ports:
            - 6379
        logging:
            driver: "local"
            options:
                max-size: 10m
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - symfony_app

    rabbitmq:
        restart: unless-stopped
        image: "rabbitmq:3-management"
        environment:
            RABBITMQ_ERLANG_COOKIE: "cluster_cookie"
            RABBITMQ_DEFAULT_USER: "USER"
            RABBITMQ_DEFAULT_PASS: "PASS"
        volumes:
            - rabbitmq-data:/bitnami/rabbitmq/mnesia
        ports:
            - "5672:5672"
            - "15672:15672"
        logging:
            driver: "local"
            options:
                max-size: 10m
        healthcheck:
            test: rabbitmq-diagnostics -q ping
            interval: 5s
            timeout: 10s
            retries: 20
        networks:
            - symfony_app

volumes:
    code:
    db_app:
    rabbitmq-data:

networks:
    symfony_app:

x-mutagen:
    sync:
        defaults:
            ignore:
                vcs: true
                paths:
                    - '.idea'
                    - .DS_Store
                    - .docker
        appCode:
            alpha: '../'
            beta: 'volume://code'
            mode: 'two-way-resolved'
            configurationBeta:
                permissions:
                    defaultOwner: "id:33"
                    defaultGroup: "id:33"
                    defaultDirectoryMode: 0755
                    defaultFileMode: 0644
#                    defaultOwner: 'id:1000'
#                    defaultGroup: 'id:1000'
